language: python
python:
    - 2.7.6

env:
    - DEPS=true

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  - cd /tmp/
  - wget https://www.cs.unm.edu/~mccune/prover9/download/LADR-2009-11A.tar.gz
  - tar -xzf LADR-2009-11A.tar.gz
  - rm LADR-2009-11A.tar.gz
  - cd -
  - cp broccoli/test/Makefile /tmp/LADR-2009-11A/provers.src
  - cp -r broccoli/test/basic /tmp/
  - cp -r broccoli/test/guidance /tmp/
  - cd /tmp/LADR-2009-11A/
  - make all
  - cd -

install:
  - sudo python setup.py clean build install

script:
  - python -m broccoli -v -i /tmp/basic/input.json

after_script:
  - ls -la /tmp
  - ls -la /tmp/basic
  - ls -la /tmp/guidance

