language: python
python:
    - 2.7

env:
    - DEPS=true

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  - cd /tmp/
  - wget https://www.cs.unm.edu/~mccune/prover9/download/LADR-2009-11A.tar.gz
  - tar -xzf LADR-2009-11A.tar.gz
  - rm LADR-2009-11A.tar.gz
  - cd -
  - cp broccoli/test/Makefile /tmp/LADR-2009-11A/provers.src
  - cp broccoli/test/*.in /tmp/
  - cd /tmp/LADR-2009-11A/
  - make all
  - cd -

install:
  - python setup.py -q build install

script:
  - python -m broccoli -v -i broccoli/test/test.json
 
