language: python
python:
    - 2.7

env:
    - DEPS=true
    
script:
  - cp broccoli/test/*.in /tmp/
  - python -m broccoli -h
  - python -m broccoli -v -i broccoli/test/input.json

install:
    - python setup.py -q clean build install
